# Generated by Django 5.2 on 2025-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviar_gmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
