# Generated by Django 5.2 on 2025-04-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviar_gmail', '0002_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=6)),
                ('code_sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_by', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
        migrations.AddField(
            model_name='deletionverification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviar_gmail.project'),
        ),
    ]
