# Generated by Django 5.2 on 2025-04-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviar_gmail', '0003_deletionverification_project_delete_projeto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('intuito', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviar_gmail.projeto')),
            ],
        ),
        migrations.DeleteModel(
            name='DeletionVerification',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
